language: node_js
node_js:
  - "8.9.4"
install:
  - yarn install
env:
  - DB_TYPE="mysql" DB_LOGGING=false
script:
  - npm start test
  - npm start test.integration
  - npm start test.e2e
  - npm start build
notifications:
  email: false
