export enum Countries {
  Afghanistan = 'AF',
  AlandIslands = 'AX',
  Albania = 'AL',
  Algeria = 'DZ',
  AmericanSamoa = 'AS',
  Andorra = 'AD',
  Angola = 'AO',
  Anguilla = 'AI',
  Antarctica = 'AQ',
  AntiguaAndBarbuda = 'AG',
  Argentina = 'AR',
  Armenia = 'AM',
  Aruba = 'AW',
  Australia = 'AU',
  Austria = 'AT',
  Azerbaijan = 'AZ',
  Bahamas = 'BS',
  Bahrain = 'BH',
  Bangladesh = 'BD',
  Barbados = 'BB',
  Belarus = 'BY',
  Belgium = 'BE',
  Belize = 'BZ',
  Benin = 'BJ',
  Bermuda = 'BM',
  Bhutan = 'BT',
  Bolivia = 'BO',
  BonaireSintEustatiusSaba = 'BQ',
  BosniaAndHerzegovina = 'BA',
  Botswana = 'BW',
  BouvetIsland = 'BV',
  Brazil = 'BR',
  BritishIndianOceanTerritory = 'IO',
  BruneiDarussalam = 'BN',
  Bulgaria = 'BG',
  BurkinaFaso = 'BF',
  Burundi = 'BI',
  Cambodia = 'KH',
  Cameroon = 'CM',
  Canada = 'CA',
  CapeVerde = 'CV',
  CaymanIslands = 'KY',
  CentralAfricanRepublic = 'CF',
  Chad = 'TD',
  Chile = 'CL',
  China = 'CN',
  ChristmasIsland = 'CX',
  CocosKeelingIslands = 'CC',
  Colombia = 'CO',
  Comoros = 'KM',
  Congo = 'CG',
  CongoDemocraticRepublic = 'CD',
  CookIslands = 'CK',
  CostaRica = 'CR',
  CoteDIvoire = 'CI',
  Croatia = 'HR',
  Cuba = 'CU',
  Curaçao = 'CW',
  Cyprus = 'CY',
  CzechRepublic = 'CZ',
  Denmark = 'DK',
  Djibouti = 'DJ',
  Dominica = 'DM',
  DominicanRepublic = 'DO',
  Ecuador = 'EC',
  Egypt = 'EG',
  ElSalvador = 'SV',
  EquatorialGuinea = 'GQ',
  Eritrea = 'ER',
  Estonia = 'EE',
  Ethiopia = 'ET',
  FalklandIslands = 'FK',
  FaroeIslands = 'FO',
  Fiji = 'FJ',
  Finland = 'FI',
  France = 'FR',
  FrenchGuiana = 'GF',
  FrenchPolynesia = 'PF',
  FrenchSouthernTerritories = 'TF',
  Gabon = 'GA',
  Gambia = 'GM',
  Georgia = 'GE',
  Germany = 'DE',
  Ghana = 'GH',
  Gibraltar = 'GI',
  Greece = 'GR',
  Greenland = 'GL',
  Grenada = 'GD',
  Guadeloupe = 'GP',
  Guam = 'GU',
  Guatemala = 'GT',
  Guernsey = 'GG',
  Guinea = 'GN',
  GuineaBissau = 'GW',
  Guyana = 'GY',
  Haiti = 'HT',
  HeardIslandMcdonaldIslands = 'HM',
  HolySeeVaticanCityState = 'VA',
  Honduras = 'HN',
  HongKong = 'HK',
  Hungary = 'HU',
  Iceland = 'IS',
  India = 'IN',
  Indonesia = 'ID',
  Iran = 'IR',
  Iraq = 'IQ',
  Ireland = 'IE',
  IsleOfMan = 'IM',
  Israel = 'IL',
  Italy = 'IT',
  Jamaica = 'JM',
  Japan = 'JP',
  Jersey = 'JE',
  Jordan = 'JO',
  Kazakhstan = 'KZ',
  Kenya = 'KE',
  Kiribati = 'KI',
  Korea = 'KR',
  KoreaDemocraticPeoplesRepublic = 'KP',
  Kuwait = 'KW',
  Kyrgyzstan = 'KG',
  LaoPeoplesDemocraticRepublic = 'LA',
  Latvia = 'LV',
  Lebanon = 'LB',
  Lesotho = 'LS',
  Liberia = 'LR',
  LibyanArabJamahiriya = 'LY',
  Liechtenstein = 'LI',
  Lithuania = 'LT',
  Luxembourg = 'LU',
  Macao = 'MO',
  Macedonia = 'MK',
  Madagascar = 'MG',
  Malawi = 'MW',
  Malaysia = 'MY',
  Maldives = 'MV',
  Mali = 'ML',
  Malta = 'MT',
  MarshallIslands = 'MH',
  Martinique = 'MQ',
  Mauritania = 'MR',
  Mauritius = 'MU',
  Mayotte = 'YT',
  Mexico = 'MX',
  Micronesia = 'FM',
  Moldova = 'MD',
  Monaco = 'MC',
  Mongolia = 'MN',
  Montenegro = 'ME',
  Montserrat = 'MS',
  Morocco = 'MA',
  Mozambique = 'MZ',
  Myanmar = 'MM',
  Namibia = 'NA',
  Nauru = 'NR',
  Nepal = 'NP',
  Netherlands = 'NL',
  NewCaledonia = 'NC',
  NewZealand = 'NZ',
  Nicaragua = 'NI',
  Niger = 'NE',
  Nigeria = 'NG',
  Niue = 'NU',
  NorfolkIsland = 'NF',
  NorthernMarianaIslands = 'MP',
  Norway = 'NO',
  Oman = 'OM',
  Pakistan = 'PK',
  Palau = 'PW',
  PalestinianTerritory = 'PS',
  Panama = 'PA',
  PapuaNewGuinea = 'PG',
  Paraguay = 'PY',
  Peru = 'PE',
  Philippines = 'PH',
  Pitcairn = 'PN',
  Poland = 'PL',
  Portugal = 'PT',
  PuertoRico = 'PR',
  Qatar = 'QA',
  Reunion = 'RE',
  Romania = 'RO',
  RussianFederation = 'RU',
  Rwanda = 'RW',
  SaintBarthelemy = 'BL',
  SaintHelena = 'SH',
  SaintKittsAndNevis = 'KN',
  SaintLucia = 'LC',
  SaintMartin = 'MF',
  SaintPierreAndMiquelon = 'PM',
  SaintVincentAndGrenadines = 'VC',
  Samoa = 'WS',
  SanMarino = 'SM',
  SaoTomeAndPrincipe = 'ST',
  SaudiArabia = 'SA',
  Senegal = 'SN',
  Serbia = 'RS',
  Seychelles = 'SC',
  SierraLeone = 'SL',
  Singapore = 'SG',
  SintMaarten = 'SX',
  Slovakia = 'SK',
  Slovenia = 'SI',
  SolomonIslands = 'SB',
  Somalia = 'SO',
  SouthAfrica = 'ZA',
  SouthGeorgiaAndSandwichIsl = 'GS',
  SouthSudan = 'SS',
  Spain = 'ES',
  SriLanka = 'LK',
  Sudan = 'SD',
  Suriname = 'SR',
  SvalbardAndJanMayen = 'SJ',
  Swaziland = 'SZ',
  Sweden = 'SE',
  Switzerland = 'CH',
  SyrianArabRepublic = 'SY',
  Taiwan = 'TW',
  Tajikistan = 'TJ',
  Tanzania = 'TZ',
  Thailand = 'TH',
  TimorLeste = 'TL',
  Togo = 'TG',
  Tokelau = 'TK',
  Tonga = 'TO',
  TrinidadAndTobago = 'TT',
  Tunisia = 'TN',
  Turkey = 'TR',
  Turkmenistan = 'TM',
  TurksAndCaicosIslands = 'TC',
  Tuvalu = 'TV',
  Uganda = 'UG',
  Ukraine = 'UA',
  UnitedArabEmirates = 'AE',
  UnitedKingdom = 'GB',
  UnitedStates = 'US',
  UnitedStatesOutlyingIslands = 'UM',
  Uruguay = 'UY',
  Uzbekistan = 'UZ',
  Vanuatu = 'VU',
  Venezuela = 'VE',
  Vietnam = 'VN',
  VirginIslandsBritish = 'VG',
  VirginIslandsUS = 'VI',
  WallisAndFutuna = 'WF',
  WesternSahara = 'EH',
  Yemen = 'YE',
  Zambia = 'ZM',
  Zimbabwe = 'ZW',
}

export const ListCountries = [
  { name: 'Afghanistan', cod: 'AF'},
  { name: 'AlandIslands', cod: 'AX'},
  { name: 'Albania', cod: 'AL'},
  { name: 'Algeria', cod: 'DZ'},
  { name: 'AmericanSamoa', cod: 'AS'},
  { name: 'Andorra', cod: 'AD'},
  { name: 'Angola', cod: 'AO'},
  { name: 'Anguilla', cod: 'AI'},
  { name: 'Antarctica', cod: 'AQ'},
  { name: 'AntiguaAndBarbuda', cod: 'AG'},
  { name: 'Argentina', cod: 'AR'},
  { name: 'Armenia', cod: 'AM'},
  { name: 'Aruba', cod: 'AW'},
  { name: 'Australia', cod: 'AU'},
  { name: 'Austria', cod: 'AT'},
  { name: 'Azerbaijan', cod: 'AZ'},
  { name: 'Bahamas', cod: 'BS'},
  { name: 'Bahrain', cod: 'BH'},
  { name: 'Bangladesh', cod: 'BD'},
  { name: 'Barbados', cod: 'BB'},
  { name: 'Belarus', cod: 'BY'},
  { name: 'Belgium', cod: 'BE'},
  { name: 'Belize', cod: 'BZ'},
  { name: 'Benin', cod: 'BJ'},
  { name: 'Bermuda', cod: 'BM'},
  { name: 'Bhutan', cod: 'BT'},
  { name: 'Bolivia', cod: 'BO'},
  { name: 'BonaireSintEustatiusSaba', cod: 'BQ'},
  { name: 'BosniaAndHerzegovina', cod: 'BA'},
  { name: 'Botswana', cod: 'BW'},
  { name: 'BouvetIsland', cod: 'BV'},
  { name: 'Brazil', cod: 'BR'},
  { name: 'BritishIndianOceanTerritory', cod: 'IO'},
  { name: 'BruneiDarussalam', cod: 'BN'},
  { name: 'Bulgaria', cod: 'BG'},
  { name: 'BurkinaFaso', cod: 'BF'},
  { name: 'Burundi', cod: 'BI'},
  { name: 'Cambodia', cod: 'KH'},
  { name: 'Cameroon', cod: 'CM'},
  { name: 'Canada', cod: 'CA'},
  { name: 'CapeVerde', cod: 'CV'},
  { name: 'CaymanIslands', cod: 'KY'},
  { name: 'CentralAfricanRepublic', cod: 'CF'},
  { name: 'Chad', cod: 'TD'},
  { name: 'Chile', cod: 'CL'},
  { name: 'China', cod: 'CN'},
  { name: 'ChristmasIsland', cod: 'CX'},
  { name: 'CocosKeelingIslands', cod: 'CC'},
  { name: 'Colombia', cod: 'CO'},
  { name: 'Comoros', cod: 'KM'},
  { name: 'Congo', cod: 'CG'},
  { name: 'CongoDemocraticRepublic', cod: 'CD'},
  { name: 'CookIslands', cod: 'CK'},
  { name: 'CostaRica', cod: 'CR'},
  { name: 'CoteDIvoire', cod: 'CI'},
  { name: 'Croatia', cod: 'HR'},
  { name: 'Cuba', cod: 'CU'},
  { name: 'Curaçao', cod: 'CW'},
  { name: 'Cyprus', cod: 'CY'},
  { name: 'CzechRepublic', cod: 'CZ'},
  { name: 'Denmark', cod: 'DK'},
  { name: 'Djibouti', cod: 'DJ'},
  { name: 'Dominica', cod: 'DM'},
  { name: 'DominicanRepublic', cod: 'DO'},
  { name: 'Ecuador', cod: 'EC'},
  { name: 'Egypt', cod: 'EG'},
  { name: 'ElSalvador', cod: 'SV'},
  { name: 'EquatorialGuinea', cod: 'GQ'},
  { name: 'Eritrea', cod: 'ER'},
  { name: 'Estonia', cod: 'EE'},
  { name: 'Ethiopia', cod: 'ET'},
  { name: 'FalklandIslands', cod: 'FK'},
  { name: 'FaroeIslands', cod: 'FO'},
  { name: 'Fiji', cod: 'FJ'},
  { name: 'Finland', cod: 'FI'},
  { name: 'France', cod: 'FR'},
  { name: 'FrenchGuiana', cod: 'GF'},
  { name: 'FrenchPolynesia', cod: 'PF'},
  { name: 'FrenchSouthernTerritories', cod: 'TF'},
  { name: 'Gabon', cod: 'GA'},
  { name: 'Gambia', cod: 'GM'},
  { name: 'Georgia', cod: 'GE'},
  { name: 'Germany', cod: 'DE'},
  { name: 'Ghana', cod: 'GH'},
  { name: 'Gibraltar', cod: 'GI'},
  { name: 'Greece', cod: 'GR'},
  { name: 'Greenland', cod: 'GL'},
  { name: 'Grenada', cod: 'GD'},
  { name: 'Guadeloupe', cod: 'GP'},
  { name: 'Guam', cod: 'GU'},
  { name: 'Guatemala', cod: 'GT'},
  { name: 'Guernsey', cod: 'GG'},
  { name: 'Guinea', cod: 'GN'},
  { name: 'GuineaBissau', cod: 'GW'},
  { name: 'Guyana', cod: 'GY'},
  { name: 'Haiti', cod: 'HT'},
  { name: 'HeardIslandMcdonaldIslands', cod: 'HM'},
  { name: 'HolySeeVaticanCityState', cod: 'VA'},
  { name: 'Honduras', cod: 'HN'},
  { name: 'HongKong', cod: 'HK'},
  { name: 'Hungary', cod: 'HU'},
  { name: 'Iceland', cod: 'IS'},
  { name: 'India', cod: 'IN'},
  { name: 'Indonesia', cod: 'ID'},
  { name: 'Iran', cod: 'IR'},
  { name: 'Iraq', cod: 'IQ'},
  { name: 'Ireland', cod: 'IE'},
  { name: 'IsleOfMan', cod: 'IM'},
  { name: 'Israel', cod: 'IL'},
  { name: 'Italy', cod: 'IT'},
  { name: 'Jamaica', cod: 'JM'},
  { name: 'Japan', cod: 'JP'},
  { name: 'Jersey', cod: 'JE'},
  { name: 'Jordan', cod: 'JO'},
  { name: 'Kazakhstan', cod: 'KZ'},
  { name: 'Kenya', cod: 'KE'},
  { name: 'Kiribati', cod: 'KI'},
  { name: 'Korea', cod: 'KR'},
  { name: 'KoreaDemocraticPeoplesRepublic', cod: 'KP'},
  { name: 'Kuwait', cod: 'KW'},
  { name: 'Kyrgyzstan', cod: 'KG'},
  { name: 'LaoPeoplesDemocraticRepublic', cod: 'LA'},
  { name: 'Latvia', cod: 'LV'},
  { name: 'Lebanon', cod: 'LB'},
  { name: 'Lesotho', cod: 'LS'},
  { name: 'Liberia', cod: 'LR'},
  { name: 'LibyanArabJamahiriya', cod: 'LY'},
  { name: 'Liechtenstein', cod: 'LI'},
  { name: 'Lithuania', cod: 'LT'},
  { name: 'Luxembourg', cod: 'LU'},
  { name: 'Macao', cod: 'MO'},
  { name: 'Macedonia', cod: 'MK'},
  { name: 'Madagascar', cod: 'MG'},
  { name: 'Malawi', cod: 'MW'},
  { name: 'Malaysia', cod: 'MY'},
  { name: 'Maldives', cod: 'MV'},
  { name: 'Mali', cod: 'ML'},
  { name: 'Malta', cod: 'MT'},
  { name: 'MarshallIslands', cod: 'MH'},
  { name: 'Martinique', cod: 'MQ'},
  { name: 'Mauritania', cod: 'MR'},
  { name: 'Mauritius', cod: 'MU'},
  { name: 'Mayotte', cod: 'YT'},
  { name: 'Mexico', cod: 'MX'},
  { name: 'Micronesia', cod: 'FM'},
  { name: 'Moldova', cod: 'MD'},
  { name: 'Monaco', cod: 'MC'},
  { name: 'Mongolia', cod: 'MN'},
  { name: 'Montenegro', cod: 'ME'},
  { name: 'Montserrat', cod: 'MS'},
  { name: 'Morocco', cod: 'MA'},
  { name: 'Mozambique', cod: 'MZ'},
  { name: 'Myanmar', cod: 'MM'},
  { name: 'Namibia', cod: 'NA'},
  { name: 'Nauru', cod: 'NR'},
  { name: 'Nepal', cod: 'NP'},
  { name: 'Netherlands', cod: 'NL'},
  { name: 'NewCaledonia', cod: 'NC'},
  { name: 'NewZealand', cod: 'NZ'},
  { name: 'Nicaragua', cod: 'NI'},
  { name: 'Niger', cod: 'NE'},
  { name: 'Nigeria', cod: 'NG'},
  { name: 'Niue', cod: 'NU'},
  { name: 'NorfolkIsland', cod: 'NF'},
  { name: 'NorthernMarianaIslands', cod: 'MP'},
  { name: 'Norway', cod: 'NO'},
  { name: 'Oman', cod: 'OM'},
  { name: 'Pakistan', cod: 'PK'},
  { name: 'Palau', cod: 'PW'},
  { name: 'PalestinianTerritory', cod: 'PS'},
  { name: 'Panama', cod: 'PA'},
  { name: 'PapuaNewGuinea', cod: 'PG'},
  { name: 'Paraguay', cod: 'PY'},
  { name: 'Peru', cod: 'PE'},
  { name: 'Philippines', cod: 'PH'},
  { name: 'Pitcairn', cod: 'PN'},
  { name: 'Poland', cod: 'PL'},
  { name: 'Portugal', cod: 'PT'},
  { name: 'PuertoRico', cod: 'PR'},
  { name: 'Qatar', cod: 'QA'},
  { name: 'Reunion', cod: 'RE'},
  { name: 'Romania', cod: 'RO'},
  { name: 'RussianFederation', cod: 'RU'},
  { name: 'Rwanda', cod: 'RW'},
  { name: 'SaintBarthelemy', cod: 'BL'},
  { name: 'SaintHelena', cod: 'SH'},
  { name: 'SaintKittsAndNevis', cod: 'KN'},
  { name: 'SaintLucia', cod: 'LC'},
  { name: 'SaintMartin', cod: 'MF'},
  { name: 'SaintPierreAndMiquelon', cod: 'PM'},
  { name: 'SaintVincentAndGrenadines', cod: 'VC'},
  { name: 'Samoa', cod: 'WS'},
  { name: 'SanMarino', cod: 'SM'},
  { name: 'SaoTomeAndPrincipe', cod: 'ST'},
  { name: 'SaudiArabia', cod: 'SA'},
  { name: 'Senegal', cod: 'SN'},
  { name: 'Serbia', cod: 'RS'},
  { name: 'Seychelles', cod: 'SC'},
  { name: 'SierraLeone', cod: 'SL'},
  { name: 'Singapore', cod: 'SG'},
  { name: 'SintMaarten', cod: 'SX'},
  { name: 'Slovakia', cod: 'SK'},
  { name: 'Slovenia', cod: 'SI'},
  { name: 'SolomonIslands', cod: 'SB'},
  { name: 'Somalia', cod: 'SO'},
  { name: 'SouthAfrica', cod: 'ZA'},
  { name: 'SouthGeorgiaAndSandwichIsl', cod: 'GS'},
  { name: 'SouthSudan', cod: 'SS'},
  { name: 'Spain', cod: 'ES'},
  { name: 'SriLanka', cod: 'LK'},
  { name: 'Sudan', cod: 'SD'},
  { name: 'Suriname', cod: 'SR'},
  { name: 'SvalbardAndJanMayen', cod: 'SJ'},
  { name: 'Swaziland', cod: 'SZ'},
  { name: 'Sweden', cod: 'SE'},
  { name: 'Switzerland', cod: 'CH'},
  { name: 'SyrianArabRepublic', cod: 'SY'},
  { name: 'Taiwan', cod: 'TW'},
  { name: 'Tajikistan', cod: 'TJ'},
  { name: 'Tanzania', cod: 'TZ'},
  { name: 'Thailand', cod: 'TH'},
  { name: 'TimorLeste', cod: 'TL'},
  { name: 'Togo', cod: 'TG'},
  { name: 'Tokelau', cod: 'TK'},
  { name: 'Tonga', cod: 'TO'},
  { name: 'TrinidadAndTobago', cod: 'TT'},
  { name: 'Tunisia', cod: 'TN'},
  { name: 'Turkey', cod: 'TR'},
  { name: 'Turkmenistan', cod: 'TM'},
  { name: 'TurksAndCaicosIslands', cod: 'TC'},
  { name: 'Tuvalu', cod: 'TV'},
  { name: 'Uganda', cod: 'UG'},
  { name: 'Ukraine', cod: 'UA'},
  { name: 'UnitedArabEmirates', cod: 'AE'},
  { name: 'UnitedKingdom', cod: 'GB'},
  { name: 'UnitedStates', cod: 'US'},
  { name: 'UnitedStatesOutlyingIslands', cod: 'UM'},
  { name: 'Uruguay', cod: 'UY'},
  { name: 'Uzbekistan', cod: 'UZ'},
  { name: 'Vanuatu', cod: 'VU'},
  { name: 'Venezuela', cod: 'VE'},
  { name: 'Vietnam', cod: 'VN'},
  { name: 'VirginIslandsBritish', cod: 'VG'},
  { name: 'VirginIslandsUS', cod: 'VI'},
  { name: 'WallisAndFutuna', cod: 'WF'},
  { name: 'WesternSahara', cod: 'EH'},
  { name: 'Yemen', cod: 'YE'},
  { name: 'Zambia', cod: 'ZM'},
  { name: 'Zimbabwe', cod: 'ZW'},
];
