export enum StatesOfBrasil {
  Acre = 'AC',
  Alagoas = 'AL',
  Amapa = 'AP',
  Amazonas = 'AM',
  Bahia = 'BA',
  Ceara = 'CE',
  DistritoFederal = 'DF',
  EspiritoSanto = 'ES',
  Goias = 'GO',
  Maranhao = 'MA',
  MatoGrosso = 'MT',
  MatoGrossoDoSul = 'MS',
  MinasGerais = 'MG',
  Para = 'PA',
  Paraiba = 'PB',
  Parana = 'PR',
  Pernambuco = 'PE',
  Piaui = 'PI',
  RiodeJaneiro = 'RJ',
  RioGrandeDoNorte  = 'RN',
  RioGrandeDoSul = 'RS',
  Rondonia = 'RO',
  Roraima = 'RR',
  SantaCatarina = 'SC',
  SaoPaulo = 'SP',
  Sergipe = 'SE',
  Tocantins = 'TO'
}

export const ListStatesOfBrasil =[
  { name: 'Acre', code: 'AC' },
  { name: 'Alagoas', code: 'AL' },
  { name: 'Amapa', code: 'AP' },
  { name: 'Amazonas', code: 'AM' },
  { name: 'Bahia', code: 'BA' },
  { name: 'Ceara', code: 'CE' },
  { name: 'DistritoFederal', code: 'DF' },
  { name: 'EspiritoSanto', code: 'ES' },
  { name: 'Goias', code: 'GO' },
  { name: 'Maranhao', code: 'MA' },
  { name: 'MatoGrosso', code: 'MT' },
  { name: 'MatoGrossoDoSul', code: 'MS' },
  { name: 'MinasGerais', code: 'MG' },
  { name: 'Para', code: 'PA' },
  { name: 'Paraiba', code: 'PB' },
  { name: 'Parana', code: 'PR' },
  { name: 'Pernambuco', code: 'PE' },
  { name: 'Piaui', code: 'PI' },
  { name: 'RiodeJaneiro', code: 'RJ' },
  { name: 'RioGrandeDoNorte ', code: 'RN' },
  { name: 'RioGrandeDoSul', code: 'RS' },
  { name: 'Rondonia', code: 'RO' },
  { name: 'Roraima', code: 'RR' },
  { name: 'SantaCatarina', code: 'SC' },
  { name: 'SaoPaulo', code: 'SP' },
  { name: 'Sergipe', code: 'SE' },
  { name: 'Tocantins', code: 'TO' }
];
